### ISSUE TITLE
GVim lacks all GUI elements?

### ISSUE THREAD

**Issue by sincere267** [vim/vim-appimage#57]
When launching `GVim-v9.0.1885.glibc2.29-x86_64.AppImage`, it lacks *all* GUI elements, such as: the toolbar, menu, and other components.

![GVim](https://github.com/vim/vim-appimage/assets/143719173/164ce029-f83f-4fe2-a5f6-77c969b42c17)

**Comment by chrisbra** [comment]
I think this is a duplicate of #55

**Comment by sincere267** [comment]
Not really, `GVim-v9.0.1894.glibc2.29-x86_64.AppImage` got the same error.

**Comment by sincere267** [comment]
Not really, `GVim-v9.0.1894.glibc2.29-x86_64.AppImage` has the same bug.

**Comment by sincere267** [comment]
Not really, `GVim-v9.0.1894.glibc2.29-x86_64.AppImage` is now running in the *terminal* mode.

![GVim](https://github.com/vim/vim-appimage/assets/143719173/4e5c5e9f-4328-43d3-8c1e-afd6c242d8f2)

**Comment by chrisbra** [comment]
I thought this was about loading the menus, etc.  Would be good if you would be clear from the beginning. Try running using `-g`

**Comment by sincere267** [comment]
Why did you close this issue when the error is *still* persisting?

```bash
$ ./GVim-v9.0.1894.glibc2.29-x86_64.AppImage -g

(gvim:18906): Gtk-WARNING **: 14:46:08.522: Could not load a pixbuf from icon theme.
This may indicate that pixbuf loaders or the mime database could not be found.
**
Gtk:ERROR:../../../../gtk/gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /usr/share/icons/Adwaita/16x16/status/image-missing.png: Unrecognized image file format (gdk-pixbuf-error-quark, 3)
Bail out! Gtk:ERROR:../../../../gtk/gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /usr/share/icons/Adwaita/16x16/status/image-missing.png: Unrecognized image file format (gdk-pixbuf-error-quark, 3)
Vim: Caught deadly signal ABRT
Vim: Finished.
E852: The child process failed to start the GUI
Press ENTER or type command to continue
```

**Comment by sincere267** [comment]
No, the error *still* exists when launching `GVim-v9.0.1897.glibc2.29-x86_64.AppImage`.

```bash
$ ./GVim-v9.0.1897.glibc2.29-x86_64.AppImage -g 

(gvim:20432): Gtk-WARNING **: <redacted>: Could not load a pixbuf from icon theme.
This may indicate that pixbuf loaders or the mime database could not be found.
**
Gtk:ERROR:../../../../gtk/gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /usr/share/icons/Adwaita/16x16/status/image-missing.png: Unrecognized image file format (gdk-pixbuf-error-quark, 3)
Bail out! Gtk:ERROR:../../../../gtk/gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /usr/share/icons/Adwaita/16x16/status/image-missing.png: Unrecognized image file format (gdk-pixbuf-error-quark, 3)
Vim: Caught deadly signal ABRT
Vim: Finished.
E852: The child process failed to start the GUI
Press ENTER or type command to continue
```

![GVim](https://github.com/vim/vim-appimage/assets/143719173/37fdd142-9685-4363-9c30-882a139aa909)

**Comment by sincere267** [comment]
I suggest ensuring that every bug is thoroughly fixed *before* closing an issue on GitHub.

**Comment by chrisbra** [comment]
Those are different problems however.

1) was not loading the correct vim runtime files. This was fixed in 25c1c4abc5696222f242b9135406a214e2c0ae26 by setting the environment variable `$VIMRUNTIME` in the appimage
2) the gvim appimage was not started in graphical mode. This can be either done by adding the startup argument `-g` or by making sure, that the `gvim` symlink is executed. Which was what 45c81c17c82bde57d634fa5871b66e44039a8262

Both of those issues have been promptly fixed.

3) what you see now, seems to come by gvim trying to load different libraries that are available on your system vs. what it was compiled with. It may also matter what is in your configuration files. However, it seems to work fine, when starting with `--clean`. So I suggest to just use this. It looks like this issue here: https://github.com/AppImageCommunity/pkg2appimage/issues/536 which we have been struggling with before and the reason how to solve it was not quite clear.

Regarding this comment: 

> I suggest ensuring that every bug is thoroughly fixed before closing an issue on GitHub.

I cannot foresee what potential bug is coming up next, just because I fix a different one. Quite honestly, you haven't provided much information other than *it doesn't work* and I have promptly addressed the issues I saw already. 

Anyway I don't really like this attitude however. Everything here is done during free time, nobody is paid for analyzing or fixing bugs as such, I find such comments not particular helpful in fixing remaining issue or even motivating me to spend my spare free time on this issue. So instead of *demanding to have issues fixed* how about you spend some time helping analyzing what is actually causing this issue and how to properly fix it?

**Comment by sincere267** [comment]
Hello @chrisbra,

> Anyway I don't really like this attitude however.

I want to clarify that my previous comment was not intended to be judgmental or negative. I simply wanted to suggest that it would be best to wait for confirmation from the bug reporter before closing a bug. I apologize if my comment hurt your feelings.

> Everything here is done during free time, nobody is paid for analyzing or fixing bugs as such, I find such comments not particular helpful in fixing remaining issue or even motivating me to spend my spare free time on this issue.

I apologize if my previous comment was not motivating. It was not my intention to diminish the hard work and dedication put into this project. I appreciate the effort you have already invested, and I will refrain from making such comments in the future.

**Comment by sincere267** [comment]
I am running your `GVim-v9.0.1897.glibc2.29-x86_64.AppImage` on my Debian 12 system with GNOME desktop. Despite starting it with `--clean`, the error persists.

I have attempted to compile `vim/vim-appimage` on my system, but I encountered the same error as your build. I have also tested them on a clean virtual machine, but I got the same output result.

**Comment by chrisbra** [comment]
thanks no problem. 

We are basically now at #50 again. This errors seems to be hard to fix. It is not clear to me, how to properly fix this for gtk applications. I tried a few things (like copying the `gdk-pixbuf` libraries, set the `GDK_PIXBUF_MODULE_FILE` env variable, updated the mime-database, etc,) all did not help.

FWIW: I see the same issue on my debian bookworm installation, where it fails with `--clean` but when I disabling loading the graphical icons, it starts okay. On a different debian system, I see the exact opposite: it fails with this error when not using `--clean` but with `--clean` it opens up a nice little gui.

At this point, I am currently out of ideas and don't know how to properly fix it. As I said, we are now basically back at #50 (which I believe is essentially the same issue).

**Comment by chrisbra** [comment]
may be we need to use https://github.com/linuxdeploy/linuxdeploy-plugin-gtk

**Comment by sincere267** [comment]
The bug has been well fixed in #60. Thank you for your hard work!

![GVim](https://github.com/vim/vim-appimage/assets/143719173/543284b8-3c9b-4000-849f-2743687599ef)

**Comment by chrisbra** [comment]
perfect thanks!
